minor typo fix
mc256/starlight pull request #53
Opened 2023-07-17 00:22 UTC by harunaadoga

Fixed a minor typo in the README file.

2023-07-17 04:29 UTC, mc256 requested changes

2023-07-17 04:29 UTC, mc256 commented on README.md
> +`<img align="right" src="docs/images/provisioning-time-wan.png">`
We need this image! Could you check how it looks?

2023-07-17 04:29 UTC, mc256 commented on README.md
> +   The Starlight format is **backwards compatible** and almost the same size, so there is no need to store compressed layers twice. In other words, non-Starlight workers will descrompress Starlight i
This is the only meaningful change...

2023-07-22 04:19 UTC, mc256 requested changes
Hi @harunaadoga, thank you for your contributions. GitHub has done the job of keeping the history of a file. Could you please remove `.history/*`? With just two typos that you want to fix and nothing more? And please review your changes in Github so that the Markdown renders correctly.

2023-07-22 06:44 UTC, harunaadoga commented
> 

Done, please feel free to ignore this since it's just two typos. Thanks!

2023-07-24 03:15 UTC, mc256 commented
Thanks, I will resolve these typos in another PR.

2023-07-24 03:15 UTC, closed without merging